過去に実施してシステムエラーが発生したテストパターンを追加
EC-CUBE/eccube3-doc pull request #110
Opened 2023-06-13 08:47 UTC by shinya

# 概要

過去にモンキーテストを実施した際にシステムエラーになるパターンを発見したものを
テストシナリオとして追加しました。

2023-06-13 23:12 UTC, chihiro-adachi commented
@shinya 
追加いただいたシナリオは、こちらの不具合に対する試験かと思います。
なので個別のシナリオを作るのではなく、スロットリングの試験シナリオとして追加するのが妥当かと思います。
https://github.com/EC-CUBE/ec-cube/issues/5957

事象としてはプラグインを削除するだけで発生するため、以下のようなシナリオを追加するとよいかと思います。

1. 任意のプラグインを削除する
1. スロットリングが設定されている機能を実行する(会員登録など)
1. システムエラーが発生せず、正常に完了できることを確認する

2023-06-14 00:59 UTC, shinya commented
@chihiro-adachi 
ご指摘ありがとうございます。
内容反映してみました。意図に即してるか確認お願いします。

2023-06-14 02:06 UTC, chihiro-adachi requested changes

2023-06-14 02:06 UTC, chihiro-adachi commented on IntegrationTest/EF03_Order_結合試験項目書.md
> +## EF0306-UC01-T01_過去エラー発生特殊テストパターン（ゲストで9種類の商品を購入）
@shinya 
こちらのシナリオも削除お願いします。

2023-06-14 02:06 UTC, chihiro-adachi commented on IntegrationTest/EF09_スロットリング_結合試験項目書.md
> +## EF0902-UC01-T01_過去エラー発生特殊テストパターン
@shinya 
`過去エラー発生特殊テストパターン`だと、何のエラーに対するテストなのかわからないので、こんな感じでいかがでしょう。

```
## EF0902-UC01-T01_プラグインを削除後スロットリングが機能することを確認する

[EC-CUBE/ec-cube#5957](https://github.com/EC-CUBE/ec-cube/issues/5957)

1. 管理画面にてオーナーズストアから、任意のプラグインをインストール→アンインストールをおこなう
1. フロント画面にて会員ログインしていない状態で、ログイン画面→パスワードの再発行を実行する（スロットリングが設定されている機能を実行）
1. システムエラーが発生することなく、再発行完了の画面に遷移できることを確認する
```

2023-06-14 05:06 UTC, chihiro-adachi approved these changes

2023-06-14 05:07 UTC, chihiro-adachi commented
@shinya 
ご対応ありがとうございます！

2023-06-19 00:37 UTC, merged