重複在庫のテストパターンを追加
EC-CUBE/eccube3-doc pull request #112
Opened 2023-09-27 02:19 UTC by dotani1111

重複して在庫が登録されてしまう問題に対処 #6029
に対応するテストを追加致しました。

2023-09-27 04:40 UTC, chihiro-adachi requested changes

2023-09-27 04:40 UTC, chihiro-adachi commented on IntegrationTest/EA03_Product_結合試験項目書.md
> +
@dotani1111 
issueへのリンクを記載いただけばわかりやすいかと思います。

2023-09-27 04:48 UTC, dotani1111 commented on IntegrationTest/EA03_Product_結合試験項目書.md
> +
以下の補足を入れるとよい。
該当のissueリンク
具体的にどのようなテストなのか。何を確認するためのテストなのか。

2023-09-27 09:51 UTC, dotani1111 commented on IntegrationTest/EA03_Product_結合試験項目書.md
> +
@chihiro-adachi 
こちら対応致しました。

2023-09-28 08:06 UTC, chihiro-adachi approved these changes

2023-09-29 04:57 UTC, kiy0taka approved these changes

2023-10-02 02:09 UTC, merged