4.1追加機能のテストを追加
EC-CUBE/eccube3-doc pull request #69
Opened 2021-08-16 09:53 UTC by chihiro-adachi

以下のテストを追加しています
- 2段階認証
- インストール
- サイトマップ

2021-08-16 10:03 UTC, okazy requested changes

2021-08-16 10:03 UTC, okazy commented on IntegrationTest/EA08_SystemInformation_結合試験項目書.md
> +## EA0803-UC03-T02_2段階認証(2段階認証の解除)
```suggestion
## EA0803-UC03-T03_2段階認証(2段階認証の解除)
```

2021-08-16 10:03 UTC, okazy commented on IntegrationTest/EF06_Other_結合試験項目書.md
> +## EF0608-UC01-T02_サイトマップ(カテゴリ)
```suggestion
## EF0608-UC01-T03_サイトマップ(カテゴリ)
```

2021-08-16 10:03 UTC, okazy commented on IntegrationTest/EF06_Other_結合試験項目書.md
> +## EF0608-UC01-T02_サイトマップ(商品)
```suggestion
## EF0608-UC01-T04_サイトマップ(商品)
```

2021-08-16 10:04 UTC, okazy commented
追加内容は問題ないと思います。

2021-08-16 12:17 UTC, chihiro-adachi commented
@okazy 
修正しました。

2021-08-17 06:04 UTC, okazy approved these changes

2021-08-17 06:04 UTC, merged

2021-08-17 06:05 UTC, okazy commented
ありがとうございます。マージしました。